---
- hosts: home_pi
  become: true

  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - name: Load configuration.
      ansible.builtin.include_vars: config.yml

    - name: Ensure apt managed packages are up to date.
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
        autoclean: true
        autoremove: true
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date.
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  roles:
    - role: energy-saving
    - role: static-ip
    - role: infothrill.rpi_boot_config
    - role: hannseman.raspbian
    - role: internet-pi
    - role: monitoring
    - role: media-server
    - role: smart-home
    - role: misc
    - role: reverse-proxy
    - role: surfshark

  vars_prompt:
    - name: system_ssh_user_password
      prompt: "Enter password for user pi"
      private: yes
      confirm: yes

    - name: postfix_sasl_password
      prompt: "Enter password for gmail account used by postfix"
      private: yes
      confirm: yes

    - name: pihole_password
      prompt: "Enter password for pi-hole"
      private: yes
      confirm: yes
