---
roles:
  - name: hannseman.raspbian
    source: https://galaxy.ansible.com
  - name: infothrill.rpi_boot_config
    source: https://galaxy.ansible.com

collections:
  - name: ansible.posix
  - name: community.docker
    version: ">=3.8.0"
  - name: community.general
