- name: Restart pantry
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/pantry/"
    state: restarted
  become: false

- name: Restart home assistant
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/ha/"
    state: restarted
  become: false
