- name: Restart pantry
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pantry/"
    build: false
    restarted: true
  become: false

- name: Docker prune
  listen: Restart pantry
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
