# Media server configuration
media_server_enable: false
media_disk_path: '/mnt/data'

## Plex media server
plex_claim_token: ''
plex_port: 32400
plex_hostname: 'plex'
plex_advertise_ip: 'http://{{ plex_hostname }}:{{ plex_port }}'
plex_allowed_networks: '192.168.1.0/24,172.16.0.0/12' # local and docker networks

## Deluge
deluge_custom_config: