- name: Installing surfshark-vpn setup dependencies
  ansible.builtin.apt:
    name:
      - openvpn
      - unzip
    state: latest
    update_cache: yes
  when: ansible_facts.os_family == "Debian"

- name: Ensure openvpn surfshark directory exists
  file:
    path: /etc/openvpn/surfshark/
    state: directory

- name: Download and extract surfshark configuration files
  unarchive:
    src: https://my.surfshark.com/vpn/api/v1/server/configurations
    remote_src: true
    dest: /etc/openvpn/surfshark/

- name: Copy surfshark chosen server configuration
  ansible.builtin.copy:
    src: "/etc/openvpn/surfshark/{{ surfshark_region }}.prod.surfshark.com_{{ surfshark_protocol }}.ovpn"
    dest: "/etc/openvpn/default.conf"
    remote_src: yes
  become: true

- name: Setup surfshark authentication file
  lineinfile: 
    dest: /etc/openvpn/auth.txt
    line: "{{ item }}"
    create: true
  with_items:
    - "{{ surfshark_username }}"
    - "{{ surfshark_password }}"

- name: Set Surfshark credentials to be obtained from file
  lineinfile:
    dest: /etc/openvpn/default.conf
    regexp: "{{ item.needle }}"
    line: "{{ item.line }}"
    create: yes
  with_items:
    - { needle: 'auth-user-pass', line: 'auth-user-pass auth.txt' }

- name: Set OpenVPN client to start automatically
  lineinfile:
    dest: "/etc/default/openvpn"
    regexp: "{{ item.needle }}"
    line: "{{ item.line }}"
  with_items:
    - { needle: '#AUTOSTART="all"', line: 'AUTOSTART="default"' }

- name: Set openvpn to start on boot
  ansible.builtin.systemd:
    name: openvpn
    state: started
    enabled: yes
