---
- name: Create home assistant folders
  ansible.builtin.file:
    path: "{{ config_dir }}/ha/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - zigbee2mqtt
    - mosquitto
  become: false

- name: Install libseccomp2 if Buster distro
  apt: 
    name: libseccomp2
    state: latest
    default_release: buster-backports
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'buster'

- name: Copy home assistant docker-compose template to Pi
  ansible.builtin.template:
    src: templates/home-assistant-docker-compose.yml.j2
    dest: "{{ config_dir }}/ha/docker-compose.yml"
    mode: 0640
  become: false
  notify: Restart home assistant

- name: Copy mosquitto configuration file
  ansible.builtin.copy:
    src: files/mosquitto.conf
    dest: "{{ config_dir }}/ha/mosquitto/mosquitto.conf"
    mode: 0644
  become: false
  notify: Restart home assistant

- name: Copy zigbee2mqtt configuration file
  ansible.builtin.copy:
    src: files/zigbee2mqtt-configuration.yml
    dest: "{{ config_dir }}/ha/zigbee2mqtt/configuration.yaml"
    mode: 0644
  become: false
  notify: Restart home assistant

- name: Ensure home assistant is running
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/ha/"
    pull: true
    build: false
  become: false

- name: Setup surfshark authentication file
  ansible.builtin.lineinfile: 
    dest: /etc/openvpn/auth.txt
    line: "{{ item }}"
    create: true
  loop:
    - "{{ surfshark_username }}"
    - "{{ surfshark_password }}"

- name: Add trusted proxies
  ansible.builtin.blockinfile:
    path: "{{ config_dir }}/ha/configuration.yaml"
    state: present
    block: |
      http:
        use_x_forwarded_for: true
        trusted_proxies:
          - 127.0.0.1
          - ::1
          - 172.16.0.0/12 # docker internal network
  become: false
  notify: Restart home assistant
