---
- name: Restart pi-hole
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/pi-hole/"
    state: restarted
  become: false

- name: Restart internet-monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/internet-monitoring/"
    state: restarted
  become: false

- name: Restart shelly-plug-prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/shelly-plug-prometheus/"
    state: restarted
  become: false

- name: Restart starlink-exporter
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/starlink-exporter/"
    state: restarted
  become: false
