---
- name: Setup Docker.
  ansible.builtin.import_tasks: docker.yml

- name: Set up Internet Monitoring.
  ansible.builtin.import_tasks: internet-monitoring.yml
  when: monitoring_enable

- name: Set up Pi Hole.
  ansible.builtin.import_tasks: pi-hole.yml
  when: pihole_enable

- name: Set up Shelly Plug Monitoring.
  ansible.builtin.import_tasks: shelly-plug.yml
  when: shelly_plug_enable

- name: Set up Air Gradient Monitoring.
  ansible.builtin.import_tasks: airgradient.yml
  when: airgradient_enable

- name: Set up Starlink Monitoring.
  ansible.builtin.import_tasks: starlink.yml
  when: starlink_enable