---
- name: Create monitoring folder
  ansible.builtin.file:
    path: "{{ config_dir }}/monitoring"
    state: directory
    mode: 0755
  become: false

- name: Copy monitoring docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/monitoring-docker-compose.yml.j2
    dest: "{{ config_dir }}/monitoring/docker-compose.yml"
    mode: 0640
  become: false
  notify: Restart monitoring

- name: Ensure monitoring is running
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/monitoring/"
    build: false
  become: false