- name: Restart media-server
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/media-server/"
    build: false
    restarted: true
  become: false

- name: Docker prune
  listen: Restart media-server
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
