- name: Restart monitoring
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/monitoring/"
    build: false
    restarted: true
  become: false

- name: Docker prune
  listen: Restart monitoring
  community.docker.docker_prune:
    containers: yes
    images: yes
    images_filters:
      dangling: false
    networks: yes
    volumes: yes
