- name: Ensure ntfs is supported
  apt:
    name: ntfs-3g
    state: present

- name: "Mount disk {{ media_disk_label }}"
  ansible.posix.mount:
    path: "{{ media_disk_path }}"
    src: "LABEL={{ media_disk_label }}"
    fstype: ntfs-3g
    state: mounted
    opts: "rw,exec,uid=1000,gid=1000,umask=007"
    boot: true
