- name: Create media-server folder on Pi
  ansible.builtin.file:
    path: "{{ config_dir }}/media-server"
    state: directory
    mode: 0755
  become: false

- name: Get user running deploy
  become: false
  local_action: command whoami
  register: user_on_host

- name: "Mount media disk {{ media_disk_label }}"
  ansible.posix.mount:
    path: "/home/{{ ansible_user }}/media-server/media"
    src: "LABEL={{ media_disk_label }}"
    fstype: ntfs
    state: mounted
    boot: true
