---
- name: Setup media storage
  ansible.builtin.import_tasks: disk_setup.yml
  when: media_server_enable

- name: Setup media server
  ansible.builtin.import_tasks: media_server.yml
  when: media_server_enable
